.TH "fixnt" 1 "February 2003" "a2ps" "Debian"
.SH NAME
fixnt \- Filter for the Windows NT postscript printer driver.
.SH SYNOPSIS
.B fixnt 
< 
.I BADFILE.ps  
>  
.I GOODFILE.ps
.SH DESCRIPTION
The Windows NT postscript driver has a tendency to make broken postscript
files, that are incompatible with psutils.  
.B fixnt
is a filter that fixes these problems, allowing the use of psnup(1).
.PP
The filter takes the broken postscript file on 
.BR stdin ,
and outputs a fixed postscript file on 
.BR stdout .
It has no other form for invocation and takes no options on the command-line.
.SH OPTIONS
.TP
.B fixnt
takes no options.
.SH BUGS
.B fixnt
does not check for NTPSOct94.  For a workaround, use a sed(1) command
to replace 'NTPSOct94' with 'NTPSOct95', like so:
.RS
sed 's/NTPSOct94/NTPSOct95/g'
.RE
This is particularly important for Windows NT 3.5 users.
.SH AUTHOR
.B fixnt
was written by Holger Bauer <Holger.Bauer@topmail.de>,
Michael Rath <rath@itsm.uni-stuttgart.de>,
and Akim Demaille <demaille@inf.enst.fr>.
.SH REPORTING BUGS
Report bugs to the Authors, but avoid sending large postscript files.
.P 
Patches are always welcome; send to <bauer@itsm.uni-stuttgart.de>.
.SH "SEE ALSO"
psnup(1), sed(1)
